---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
baseurl:
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:              "City Evangelical Church"
keywords:           "City, evangelical, church, Leeds, best, christian, Jesus, bible, gospel, Christ, God, Faith, Lord"
description:        "We are a bible belieiving church in Beeston, Leeds who proclaim that Jesus is Lord, raised for the dead and the gospel is good news!"
source_link:        "https://github.com/cecleeds"
favicon:            "/assets/img/favicon/favicon.ico"
favicon_16:         "/assets/img/favicon/favicon-16x16.png"
favicon_32:         "/assets/img/favicon/favicon-32x32.png"
touch_icon:         "/assets/img/favicon/apple-touch-icon.png" ## City logo as apple touch icon
safari_pinned_tab:  "/assets/img/favicon/safari-pinned-tab.svg" ## put safari pinned tab svg icon here

google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  white:        '#f8f8f8'
  black:        '#2e2e2e'
  intro:        '#428bca'
  events:       '#ed7950'
  imnew:        '#66b266'
  aboutus:      '#5ea06e'
  sermons:      '#578e77'
  video:        '#4f7c80'
  thursday:     '#486a89'
  friday:       '#415992'
  saturday-two: '#39479b'
  contacts:     '#3035A4'
  ckyellow:     '#febd2e'
  ckblue:       '#01a8ff'
  teal:         '#009688'
  mint:       '#6cc99c'
  peach:      '#e57373'
  pink:       '#e91e63'
  darkpink:   '#c2185b'
  purple:     '#c869bf'
  cityorange: '#f29526'
  cityblue:   '#009ddf'

kramdown:
  auto_ids:  false

collections:

sass:
  sass_dir: stylesheets/_sass/

jekyll_get_json:
  - data: cscalendar
    json: 'https://cecleeds.churchsuite.co.uk/embed/calendar/json'
